# All mitmproxy options are listed and explained at
# https://docs.mitmproxy.org/stable/concepts-options/

# Replay server responses from a saved file. Type sequence of str.
server_replay: [
  "./flows/antennapod",
  # Added new interactions (and thus new requests) to the first replay
  # Subscribing and visiting podcasts
  "./flows/antennapod_2",
  "./flows/hillffair",
  "./flows/materialistic",
  "./flows/newsblur",
  "./flows/redreader",
  "./flows/travelmate",
  # Added new interactions (and thus new requests) to the first replay
  # Visit more activities and check notifications
  # Also attempt to record login again
  "./flows/travelmate_2",
  "./flows/uob",
]

# Don't remove flows from server replay state after use. This makes it
# possible to replay same response multiple times. Type bool.
# Ensures the request is replayed for all runs
server_replay_nopop: true

# Request's parameters to be ignored while searching for a saved flow to
# replay. Type sequence of str.
# Ensures that requests are matched
server_replay_ignore_params: [
  # App: Materialistic.
  # Timestamp based field.
  "numericFilters",

  # App: Materialistic.
  # Timestamp based field.
  "ts",
]

# Kill extra requests during replay. Type bool.
# Ensures that only requests that matches the replay are executed.
# Non-matched requests default to timeout
server_replay_kill_extra: true

# Stream flows to file as they arrive. Prefix path with + to append.
# Default: None 
save_stream_file: "+./output/flows"

# Ignore request's content while searching for a saved flow to replay.
# Type bool.
# This flag is required to login to Travel Mate.
# Start the server with the flag on while logging in to Travel Mate and disable it after logged in for all treatments.
# Since we have a long waiting time after the login there should be enough time for reseting the server.
# server_replay_ignore_content: true