# Replay server responses from a saved file. Type sequence of str.
server_replay: [
  "./flows/test_uob",
  "./flows/test_redreader",
  "./flows/test_materialistic",
]

# Don't remove flows from server replay state after use. This makes it
# possible to replay same response multiple times. Type bool.
server_replay_nopop: true
